---
title: Catalytik traduction
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: jessika@catalytiktraduction.com
description: 'Catalytik traduction scientifique et technique.

'
baseurl: 
url: 
permalink: pretty
plugins:
- jekyll-polyglot
languages:
- fr
- en
exclude_from_localization:
- js
- images
- css
- assets
parallel_localization: false
default_lang: fr
markdown: kramdown
menu:
  accueil:
    fr: Accueil
    en: Home
  propos:
    fr: À propos
    en: Who am I?
  nouvelles:
    fr: Nouvelles
    en: News
