# Site settings
title: Catalytik traduction
email: jessika@catalytiktraduction.com
description: > # this means to ignore newlines until "baseurl:"
 Catalytik traduction scientifique et technique.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

permalink: pretty
plugins: [jekyll-polyglot]

languages: ["fr", "en"]
exclude_from_localization: ["js", "images", "css","assets"]
parallel_localization: false
default_lang: "fr"

# Build settings
markdown: kramdown



menu:
  accueil:
    fr: Accueil
    en: Home
  propos:
    fr: À propos
    en: Who am I?
  nouvelles:
    fr: Nouvelles
    en: News
